"""Produces the Finding's prose fields. The only genuinely open-ended LLM
generation in this pipeline -- appropriate here since it's producing explanatory
text, not an executable artifact. `question` and `sql` are filled from the actual
inputs in code, never regenerated by the model, so there's no way for the
narrative to drift from what was actually asked or actually run.
"""

import json
from typing import Any

from langfuse import observe
from openai import OpenAI

from talk_to_your_data.llm import (
    ToolSpec,
    first_tool_call,
    get_client,
    get_model,
    reasoning_config,
    to_openai_tool,
)
from talk_to_your_data.tracing import record_generation

from .state import AnalysisResult, Finding, SqlResult

WRITE_FINDING_TOOL: ToolSpec = {
    "name": "write_finding",
    "description": "Write up the result of a data analysis as a business-readable finding.",
    "input_schema": {
        "type": "object",
        "properties": {
            "result_summary": {
                "type": "string",
                "description": "The number/table, summarized plainly -- not a raw data dump.",
            },
            "interpretation": {
                "type": "string",
                "description": (
                    "One or two sentences of business meaning -- so what, not a "
                    "restatement of the number."
                ),
            },
            "caveats": {
                "type": "string",
                "description": (
                    "Anything limiting how much weight this answer should carry "
                    "(filtered statuses, small sample, a known data-quality issue, "
                    "an assumed date range). Say 'none known' if genuinely none."
                ),
            },
            "confidence": {"type": "string", "enum": ["low", "medium", "high"]},
        },
        "required": ["result_summary", "interpretation", "caveats", "confidence"],
    },
}


@observe(name="write_finding", as_type="generation")
def write_finding(
    question: str,
    sql_result: SqlResult,
    analysis_result: AnalysisResult | None,
    *,
    client: OpenAI | None = None,
    model: str | None = None,
) -> Finding:
    client = client or get_client()
    model = model or get_model()

    prompt = (
        "Write up this data analysis as a finding. Every number in your "
        "interpretation must trace back to the result or analysis below -- if it "
        "doesn't, it doesn't belong. You must call write_finding to respond.\n\n"
        f"Question: {question}\n"
        f"Result columns: {sql_result.columns}\n"
        f"Result rows: {json.dumps(sql_result.rows, default=str)}\n"
        "Analysis: "
        f"{json.dumps(analysis_result.model_dump(mode='json') if analysis_result else None)}"
    )
    response = client.responses.create(
        model=model,
        max_output_tokens=8192,
        reasoning=reasoning_config(),
        tools=[to_openai_tool(WRITE_FINDING_TOOL)],
        input=[{"role": "user", "content": prompt}],
    )
    record_generation(response)
    tool_use = first_tool_call(response)
    if tool_use is None:
        raise RuntimeError("narrative_agent: model did not call write_finding")
    fields: dict[str, Any] = dict(tool_use.arguments)

    return Finding(
        question=question,
        sql=sql_result.sql,
        result_summary=str(fields["result_summary"]),
        caveats=str(fields["caveats"]),
        confidence=fields["confidence"],
        interpretation=str(fields["interpretation"]),
    )
